In [2]:
import numpy as np
import torch

### 1. 按内容创建张量
- 传入什么内容，输出格式就是什么类型

In [5]:
tensor1 = torch.tensor(10.0)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)


tensor(10.)
torch.Size([])
torch.float32


In [9]:
# 传入一个一维数组
tensor2 = torch.tensor([1.0, 2, 3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

# 传入一个二维数组
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)


tensor([1., 2., 3.])
torch.Size([3])
torch.float32
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


### 2. 创建指定形状的张量
- 大写的**Tensor**,传入形状
- 大写的**Tensor**,传入数据

注意不论是哪一种写法最后的数据格式都是float32

In [10]:
# 底层元素是一个2*4的矩阵，然后有三个这样的矩阵
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
# 创建出来的张量默认float32
print(tensor1.dtype)

tensor([[[1.3985e-33, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [11]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


### 3. 按照类型创建张量

In [13]:
# 创建整数类型
# LongIntTensor-int64; ShortIntTensor-int16; ByteIntTensor-int8
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int64


In [15]:
# 创建浮点类型
# 单精度float; 双精度 double; 半精度 half
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float64
torch.float64


In [3]:
# 创建布尔类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.bool
torch.bool
tensor([[ True, False,  True],
        [ True, False, False]])


### 4. 创建指定区间的张量
- 设置一个起始点和终止点，设置步长来创建张量

In [9]:
# 注意起始点包含，结束点不包含，左闭右开
tensor1 = torch.arange(10,30,2)
print(tensor1)
# 不写起始点默认是0，不写结束点默认是无穷大，不写步长默认是1
tensor2 = torch.arange(10)
print(tensor2)
# 按照区间内的元素数量创建张量
tensor3 = torch.linspace(10, 30, 5)
print(tensor3)
# 在指定区间内按照指定的底数创建张量，base=X表示为X底数
tensor4 = torch.logspace(10, 30, 5, base=torch.e)
print(tensor4)


tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10., 15., 20., 25., 30.])
tensor([2.2026e+04, 3.2690e+06, 4.8517e+08, 7.2005e+10, 1.0686e+13])


### 5. 按照数值填充张量

In [13]:
# 创建全0张量
tensor1 = torch.zeros(2, 3)
print(tensor1)
# 创建全1张量
tensor2 = torch.ones(2, 3)
print(tensor2)
# 创建指定形状张量，按照指定值填充，传入的填充值是什么类型的，最后创建出来的张量就是是什么类型的
tensor3 = torch.full((2, 3), 5)
print(tensor3)
# 创建指定形状的未初始化的张量
tensor4 = torch.empty(2, 3)
print(tensor4)
# 创建与指定张量形状相同的全0张量
tensor5 = torch.zeros_like(tensor1)
print(tensor5)
# 创建与指定张量形状相同的全1张量
tensor6 = torch.ones_like(tensor1)
print(tensor6)
# 创建与指定张量形状相同的未初始化的张量
tensor7 = torch.empty_like(tensor1)
print(tensor7)
# 创建与指定张量形状相同的张量，按照指定值填充
tensor8 = torch.full_like(tensor1, 5)
print(tensor8)

# 创建单位矩阵
tensor9 = torch.eye(3)
print(tensor9)
# 如果不想创建方针，可以再加一个参数
tensor10 = torch.eye(3, 5)
print(tensor10)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5]])
tensor([[5.8571e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0048, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


### 6. 创建随机张量

In [25]:
# 创建随机张量
tensor1 = torch.rand(2, 3)
print(tensor1)
# 创建与指定的张量类型相同的随机张量
tensor2 = torch.rand_like(tensor1)
print(tensor2)
# 创建随机张量，但是填充的数据是随机均匀分布的整数
tensor3 = torch.randint(low=0, high=100, size=(2, 3))
print(tensor3)
# 创建与指定张量类型相同的随机张量，但是用整数随机填充
tensor4 = torch.randint_like(tensor1, low=0, high=100)
print(tensor4)

# 创建满足标准正太分布的随机张量
tensor5 = torch.randn(2, 3)
print(tensor5)

# 创建自定义正太分布的张量
tensor6 = torch.normal(mean=0, std=1, size=(2, 3))
print(tensor6)


# 随机洗牌，打乱张量的元素顺序，每次运行的结果都不一样，就像是shuffle一样
tensor7 = torch.randperm(10)
print(tensor7)
# 这里设置随机数种子(查看和赋值)
print(torch.random.initial_seed())
torch.manual_seed(42)
print(torch.random.initial_seed())


tensor([[0.9546, 0.6340, 0.4669],
        [0.9021, 0.3310, 0.2918]])
tensor([[0.9103, 0.9249, 0.1699],
        [0.3736, 0.8161, 0.7085]])
tensor([[65, 42, 74],
        [59, 89, 41]])
tensor([[10., 93.,  8.],
        [37., 75., 66.]])
tensor([[ 0.1703, -0.0074,  0.0151],
        [ 0.1469,  0.3594, -0.0905]])
tensor([[-0.4343,  0.3171,  0.2460],
        [ 0.9075,  0.1478, -1.9565]])
tensor([5, 1, 3, 6, 7, 4, 9, 8, 2, 0])
16823401994472898239
42
