# 第二节 张量的转换

In [ ]:
import numpy as np
import torch

### 张量的类型转换

In [7]:
tensor1 = torch.tensor([1,2,3])
print('转换前的类型:',tensor1.dtype)

tensor1 = tensor1.type(torch.float32)
print('转换后的类型:',tensor1.dtype)

# PyTorch有一个特殊的数据类型，复数类型(实数虚数合在一起的类型)，torch.complex64和torch.complex128
tensor1 = tensor1.to(torch.complex64)
print(tensor1)
print('转换成复数类型的:',tensor1.dtype)

转换前的类型: torch.int64
转换后的类型: torch.float32
tensor([1.+0.j, 2.+0.j, 3.+0.j])
转换成复数类型的: torch.complex64


### 1.Tensor和ndarray之间相互转换
- 原理是共享内存：就是**数据存放在内存的某一个区间**，然后ndarray指向这部分内存中的数据，并且tensor也是指向这部分内存的数据
    - 共享内存可能会导致，本来tensor不想修改数据，但是ndarray修改完成了数据，所以为了避免数据不一致，会采用`copy()`来避免共享内存造成的问题，缺点是占用更多的内存

In [ ]:
np.set_printoptions(precision=2) # 设置numpy的打印精度
torch.set_printoptions(precision=2) # 设置torch的打印精度

In [ ]:
# Tensor和ndarray相互转换
tensor1 = torch.rand(3,2)
print('tensor1转换之前的样子:',tensor1)
# 转换之后精度不一样，可以设置精度
ndarray1 = tensor1.numpy()
print('tensor1转换成ndarray的样子:',ndarray1)

tensor1转换之前的样子: tensor([[0.4048, 0.5672],
        [0.7347, 0.6889],
        [0.7361, 0.6561]])
tensor1转换成ndarray的样子: [[0.40478218 0.5672268 ]
 [0.7346988  0.68890184]
 [0.7361349  0.65613884]]


In [ ]:
# 修改ndarray1的值，tensor1的值也会改变
tensor1[:,0] = 10
print('修改后tensor1的值:\n',tensor1)
print('ndarray1的值也会随之改变:\n',ndarray1)

修改后tensor1的值:
 tensor([[10.0000,  0.5672],
        [10.0000,  0.6889],
        [10.0000,  0.6561]])
ndarray1的值也会随之改变:
 [[10.          0.5672268 ]
 [10.          0.68890184]
 [10.          0.65613884]]


In [13]:
# 使用Copy方法，修改ndarray1的值，tensor1的值不会改变
tensor1 = torch.rand(3,2)
print('tensor1转换之前的样子:\n',tensor1)
ndarray1 = tensor1.numpy()
print('ndarray1的样子:',ndarray1)
ndarray2 = tensor1.numpy().copy()
print('ndarray2的样子:\n',ndarray2)
tensor1[:,0] = 5
print('修改后tensor1的值:\n',tensor1)
print('ndarray1的值也会随之改变:\n',ndarray1)
print('ndarray2的值不会随之改变:\n',ndarray2)

tensor1转换之前的样子:
 tensor([[0.2355, 0.3804],
        [0.0786, 0.2866],
        [0.3594, 0.0602]])
ndarray1的样子: [[0.23546469 0.38035542]
 [0.07862276 0.28664452]
 [0.3594358  0.06022227]]
ndarray2的样子:
 [[0.23546469 0.38035542]
 [0.07862276 0.28664452]
 [0.3594358  0.06022227]]
修改后tensor1的值:
 tensor([[5.0000, 0.3804],
        [5.0000, 0.2866],
        [5.0000, 0.0602]])
ndarray1的值也会随之改变:
 [[5.         0.38035542]
 [5.         0.28664452]
 [5.         0.06022227]]
ndarray2的值不会随之改变:
 [[0.23546469 0.38035542]
 [0.07862276 0.28664452]
 [0.3594358  0.06022227]]


In [14]:
# ndarray转换成tensor
ndarray1 = np.random.randn(3,2)
tensor1 = torch.from_numpy(ndarray1)
print('ndarray1的样子:\n',ndarray1)
print('ndarray1转换成tensor1的样子:\n',tensor1)

ndarray1的样子:
 [[ 2.0175116   0.53576974]
 [ 1.27400012 -0.87187358]
 [-0.36151488  0.28200276]]
ndarray1转换成tensor1的样子:
 tensor([[ 2.0175,  0.5358],
        [ 1.2740, -0.8719],
        [-0.3615,  0.2820]], dtype=torch.float64)


In [15]:
# 使用copy方法避免内存共享
tensor2 = torch.from_numpy(ndarray1.copy())

ndarray1[:,0] = 10
print('修改后ndarray1的值:\n',ndarray1)
print('tensor1的值也会随之改变:\n',tensor1)
print('tensor2的值不会随之改变:\n',tensor2)


修改后ndarray1的值:
 [[10.          0.53576974]
 [10.         -0.87187358]
 [10.          0.28200276]]
tensor1的值也会随之改变:
 tensor([[10.0000,  0.5358],
        [10.0000, -0.8719],
        [10.0000,  0.2820]], dtype=torch.float64)
tensor2的值不会随之改变:
 tensor([[ 2.0175,  0.5358],
        [ 1.2740, -0.8719],
        [-0.3615,  0.2820]], dtype=torch.float64)


#### 直接将ndarray转换为tensor，不共享内存的
 - 使用`torch.tensor(ndarray)`方法, 不用每次都调用`Copy()`方法，更加简便

In [16]:
ndarray1 = np.random.randn(3,2)
tensor1 = torch.tensor(ndarray1)
print('ndarray1的样子:\n',ndarray1)
print('ndarray1转换成tensor1的样子:\n',tensor1)

ndarray1的样子:
 [[ 0.01586965  0.8133352 ]
 [ 0.78731047  0.82019755]
 [-0.52750444 -0.37810239]]
ndarray1转换成tensor1的样子:
 tensor([[ 0.0159,  0.8133],
        [ 0.7873,  0.8202],
        [-0.5275, -0.3781]], dtype=torch.float64)


### 2. 张量Tensor和标量之间的转换
- 标量：只有一个元素
- **转换的前提是：** 张量中只有一个元素

In [19]:
tensor = torch.tensor([10])
print('tensor的样子:\n',tensor)
print('转换为标量的样子:\n',tensor.item())

tensor的样子:
 tensor([10])
转换为标量的样子:
 10
