# 张量的数值运算

数值运算
- 加减乘除
- add(),sub(),mul(),div() 不改变原数据
- add_(),sub_(),mul_(),div_() 修改原数据
- `-`,`neg()`,`neg_()`取负数(相反数)
- `**`,`pow()`,`pow_()`求幂，幂函数
- `exp()`,`exp_()`以e为底的指数运算
- `log()`,`log_()`以e为底的对数运算
- `sqrt()`,`sqrt_()`平方根运算

**注意：** 进行数值运算的时候*整数*有可能会转换为*浮点数*所以记得提前转换数值类型`dtype=`或者`.float()`

In [1]:
import torch

In [2]:
# 1. 四则运算
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print("Tensor 1:", tensor1)

Tensor 1: tensor([[8, 2, 6],
        [0, 7, 5]])


In [3]:
# 加法
tensor2 = tensor1 + 10
print("tensor2:", tensor2)

tensor2 = tensor1.add(10)
print("tensor2:", tensor2)

tensor2: tensor([[18, 12, 16],
        [10, 17, 15]])
tensor2: tensor([[18, 12, 16],
        [10, 17, 15]])


In [4]:
# 减法
tensor2 = tensor1 - 5
print("减法(-):", tensor2)

tensor2 = tensor1.sub(5)
print("sub():", tensor2)

减法(-): tensor([[ 3, -3,  1],
        [-5,  2,  0]])
sub(): tensor([[ 3, -3,  1],
        [-5,  2,  0]])


In [5]:
# 乘法
tensor2 = tensor1 * 3
print("乘法(*):", tensor2)

tensor2 = tensor1.mul(3)
print("mul():", tensor2)

乘法(*): tensor([[24,  6, 18],
        [ 0, 21, 15]])
mul(): tensor([[24,  6, 18],
        [ 0, 21, 15]])


In [8]:
# 除法
tensor_special = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float32)
tensor2 = tensor_special / 2
print("除法(/):", tensor2)

tensor2 = tensor1.div(2)
print("div():", tensor2)

print("原始 tensor1:", tensor1)

除法(/): tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
div(): tensor([[15.,  9., 13.],
        [ 7., 14., 12.]])
原始 tensor1: tensor([[30, 18, 26],
        [14, 28, 24]])


In [9]:
# 原地修改 (in-place)
print("\n--- 原地修改 ---")
tensor1.add_(10)
print("add_(10):", tensor1)

tensor1.sub_(3)
print("sub_(3):", tensor1)

tensor1.mul_(2)
print("mul_(2):", tensor1)

tensor_special.div_(4)
print("div_(4):", tensor_special)


--- 原地修改 ---
add_(10): tensor([[40, 28, 36],
        [24, 38, 34]])
sub_(3): tensor([[37, 25, 33],
        [21, 35, 31]])
mul_(2): tensor([[74, 50, 66],
        [42, 70, 62]])
div_(4): tensor([[0.2500, 0.5000, 0.7500],
        [1.0000, 1.2500, 1.5000]])


In [10]:
# 2. 取负数（相反数）
tensor_neg = torch.randint(low=0, high=10, size=(2, 3))
print("原始 tensor:", tensor_neg)

tensor2 = -tensor_neg
print("取负数(-):", tensor2)

tensor2 = tensor_neg.neg()
print("neg():", tensor2)

print("原始 tensor 未变:", tensor_neg)

# 原地取负
tensor_neg.neg_()
print("neg_():", tensor_neg)

原始 tensor: tensor([[8, 1, 0],
        [3, 8, 2]])
取负数(-): tensor([[-8, -1,  0],
        [-3, -8, -2]])
neg(): tensor([[-8, -1,  0],
        [-3, -8, -2]])
原始 tensor 未变: tensor([[8, 1, 0],
        [3, 8, 2]])
neg_(): tensor([[-8, -1,  0],
        [-3, -8, -2]])


In [11]:
# 3. 求幂（幂函数）
tensor_pow = torch.randint(low=1, high=5, size=(2, 3))
print("原始 tensor:", tensor_pow)

tensor2 = tensor_pow ** 3
print("求幂(**3):", tensor2)

tensor2 = tensor_pow.pow(3)
print("pow(3):", tensor2)

print("原始 tensor 未变:", tensor_pow)

# 原地求幂
tensor_pow.pow_(2)
print("pow_(2):", tensor_pow)

原始 tensor: tensor([[2, 2, 3],
        [3, 3, 4]])
求幂(**3): tensor([[ 8,  8, 27],
        [27, 27, 64]])
pow(3): tensor([[ 8,  8, 27],
        [27, 27, 64]])
原始 tensor 未变: tensor([[2, 2, 3],
        [3, 3, 4]])
pow_(2): tensor([[ 4,  4,  9],
        [ 9,  9, 16]])


In [12]:
# 4. 以e为底的指数运算
tensor_exp = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]])
print("原始 tensor:", tensor_exp)

tensor2 = tensor_exp.exp()
print("exp():", tensor2)

print("原始 tensor 未变:", tensor_exp)

# 原地指数
tensor_exp.exp_()
print("exp_():", tensor_exp)

原始 tensor: tensor([[0., 1., 2.],
        [3., 4., 5.]])
exp(): tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])
原始 tensor 未变: tensor([[0., 1., 2.],
        [3., 4., 5.]])
exp_(): tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])


In [13]:
# 5. 以e为底的对数运算
tensor_log = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("原始 tensor:", tensor_log)

tensor2 = tensor_log.log()
print("log():", tensor2)

print("原始 tensor 未变:", tensor_log)

# 原地对数
tensor_log.log_()
print("log_():", tensor_log)

原始 tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
log(): tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
原始 tensor 未变: tensor([[1., 2., 3.],
        [4., 5., 6.]])
log_(): tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [14]:
# 6. 平方根运算
tensor_sqrt = torch.tensor([[1.0, 4.0, 9.0], [16.0, 25.0, 36.0]])
print("原始 tensor:", tensor_sqrt)

tensor2 = tensor_sqrt.sqrt()
print("sqrt():", tensor2)

print("原始 tensor 未变:", tensor_sqrt)

# 原地平方根
tensor_sqrt.sqrt_()
print("sqrt_():", tensor_sqrt)

原始 tensor: tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
sqrt(): tensor([[1., 2., 3.],
        [4., 5., 6.]])
原始 tensor 未变: tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
sqrt_(): tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 矩阵之间的运算

1. 两个矩阵之间对应元素位置相乘称为哈达玛积(Hadamard Product)
$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

$$
A \circ B =
\begin{bmatrix}
1 \times 5 & 2 \times 6 \\
3 \times 7 & 4 \times 8
\end{bmatrix}
=
\begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix}
$$

- 要求：两个矩阵必须形状相同
- 使用`*`，`mul()`实现
- 使用hadamard product的主要作用是*逐元素地控制矩阵里的每一个位置：该保留的保留，该削弱的削弱，该放大的放大* 就像是*局部调节器*

---

2. 矩阵乘法运算
- `mm()`严格用于二维矩阵相乘
- `@`和`matmul()`支持多维张量，不同维度的矩阵可能会有broadcasting机制

设：

$$
A =
\left[
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\right]
$$

所以：

$$
A.shape = (2,2,2)
$$

再设：

$$
B =
\left[
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\right]
$$

所以：

$$
B.shape = (1,2,3)
$$

`A` 里面有两个 $2 \times 2$ 矩阵：

$$
A[0] =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

$$
A[1] =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

但是 `B` 里面只有一个 $2 \times 3$ 矩阵：

$$
B[0] =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

由于broadcasting，`B[0]`会被利用两次
$$
C[0] = A[0] @ B[0]
$$

$$
C[1] = A[1] @ B[0]
$$

$$
C[0] =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
@
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
1 \times 1 + 2 \times 4 &
1 \times 2 + 2 \times 5 &
1 \times 3 + 2 \times 6 \\

3 \times 1 + 4 \times 4 &
3 \times 2 + 4 \times 5 &
3 \times 3 + 4 \times 6
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
9 & 12 & 15 \\
19 & 26 & 33
\end{bmatrix}
$$
$$
C[1] =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
@
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
5 \times 1 + 6 \times 4 &
5 \times 2 + 6 \times 5 &
5 \times 3 + 6 \times 6 \\

7 \times 1 + 8 \times 4 &
7 \times 2 + 8 \times 5 &
7 \times 3 + 8 \times 6
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
29 & 40 & 51 \\
39 & 54 & 69
\end{bmatrix}
$$

因此：

$$
C =
\left[
\begin{bmatrix}
9 & 12 & 15 \\
19 & 26 & 33
\end{bmatrix},
\begin{bmatrix}
29 & 40 & 51 \\
39 & 54 & 69
\end{bmatrix}
\right]
$$

所以：

$$
C.shape = (2,2,3)
$$

---

In [2]:
# 1. 哈达玛积：对应位置逐元素相乘
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

print("A:")
print(A)
print("B:")
print(B)

print("A * B:")
print(A * B)

print("A.mul(B):")
print(A.mul(B))


A:
tensor([[1, 2],
        [3, 4]])
B:
tensor([[5, 6],
        [7, 8]])
A * B:
tensor([[ 5, 12],
        [21, 32]])
A.mul(B):
tensor([[ 5, 12],
        [21, 32]])


In [5]:
# 2. mm(): 只用于二维矩阵乘法
C = torch.tensor([[1, 2, 3], [4, 5, 6]])
D = torch.tensor([[1, 2], [3, 4], [5, 6]])

print("C.shape:", C.shape)
print("D.shape:", D.shape)
print("C.mm(D):", C.mm(D))

C.shape: torch.Size([2, 3])
D.shape: torch.Size([3, 2])
C.mm(D): tensor([[22, 28],
        [49, 64]])


In [7]:
# 3. @ 和 matmul(): 支持批量矩阵乘法，并且可以触发 broadcasting
batch_A = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
])
batch_B = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
])

print("batch_A.shape:", batch_A.shape)
print("batch_B.shape:", batch_B.shape)

result_at = batch_A @ batch_B
result_matmul = torch.matmul(batch_A, batch_B)

print("batch_A @ batch_B:")
print(result_at)
print("result_at.shape:", result_at.shape)

print("torch.matmul(batch_A, batch_B):")
print(result_matmul)


batch_A.shape: torch.Size([2, 2, 2])
batch_B.shape: torch.Size([1, 2, 3])
batch_A @ batch_B:
tensor([[[ 9, 12, 15],
         [19, 26, 33]],

        [[29, 40, 51],
         [39, 54, 69]]])
result_at.shape: torch.Size([2, 2, 3])
torch.matmul(batch_A, batch_B):
tensor([[[ 9, 12, 15],
         [19, 26, 33]],

        [[29, 40, 51],
         [39, 54, 69]]])
