# 张量维度交换

在上一节中，我们发现：使用布尔索引筛选满足条件的元素时，返回结果的形状不一定与原张量保持一致，因此有时无法直接用 `tensor[mask]` 按预期展示筛选结果。为了更灵活地调整张量的形状和维度顺序，我们需要学习张量的维度交换操作。除了常见的 `.T` 转置和 `.mT` 矩阵转置之外，PyTorch 还提供了更通用的维度调整方法：

- `transpose()`：交换两个维度
- `permute()`：按指定顺序重新排列多个维度
- `.T`：常用于二维张量，相当于普通矩阵转置，会交换行和列。
- `.mT`：用于矩阵转置。对于三维及以上张量，它只转置最后两个维度，前面的批次维度保持不变。

In [17]:
import torch

In [18]:
tensor1 = torch.randint(1, 10, (2,3,6))
print("tensor1:", tensor1)

tensor1: tensor([[[7, 3, 1, 8, 3, 1],
         [8, 5, 9, 8, 8, 5],
         [7, 3, 3, 9, 3, 4]],

        [[3, 4, 4, 9, 3, 4],
         [5, 3, 3, 6, 3, 3],
         [6, 8, 8, 6, 3, 3]]])


In [19]:
# .T：二维张量转置，交换行和列
tensor2 = torch.arange(1, 7).reshape(2, 3)

print("原始二维张量:")
print(tensor2)
print("原始形状:", tensor2.shape)

print("\n使用 .T 转置后:")
print(tensor2.T)
print("转置后的形状:", tensor2.T.shape)

原始二维张量:
tensor([[1, 2, 3],
        [4, 5, 6]])
原始形状: torch.Size([2, 3])

使用 .T 转置后:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
转置后的形状: torch.Size([3, 2])


In [20]:
# .mT：矩阵转置，只交换最后两个维度
tensor3 = torch.arange(1, 25).reshape(2, 3, 4)

print("原始三维张量:")
print(tensor3)
print("原始形状:", tensor3.shape)

print("\n使用 .mT 转置后:")
print(tensor3.mT)
print("转置后的形状:", tensor3.mT.shape)

原始三维张量:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
原始形状: torch.Size([2, 3, 4])

使用 .mT 转置后:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
转置后的形状: torch.Size([2, 4, 3])


In [21]:
# 交换两个维度
print("交换第1维和第2维", tensor1.transpose(1, 2))
print("交换维度后的形状:", tensor1.transpose(1, 2).shape)

交换第1维和第2维 tensor([[[7, 8, 7],
         [3, 5, 3],
         [1, 9, 3],
         [8, 8, 9],
         [3, 8, 3],
         [1, 5, 4]],

        [[3, 5, 6],
         [4, 3, 8],
         [4, 3, 8],
         [9, 6, 6],
         [3, 3, 3],
         [4, 3, 3]]])
交换维度后的形状: torch.Size([2, 6, 3])


In [22]:
# 重新排列多个维度
print("重新排列维度", tensor1.permute(2, 0, 1))
print("重新排列维度后的形状:", tensor1.permute(2, 0, 1).shape)

重新排列维度 tensor([[[7, 8, 7],
         [3, 5, 6]],

        [[3, 5, 3],
         [4, 3, 8]],

        [[1, 9, 3],
         [4, 3, 8]],

        [[8, 8, 9],
         [9, 6, 6]],

        [[3, 8, 3],
         [3, 3, 3]],

        [[1, 5, 4],
         [4, 3, 3]]])
重新排列维度后的形状: torch.Size([6, 2, 3])


## 张量的调整形状

除了交换维度之外，我们还经常需要在不改变数据内容的前提下，重新组织张量的形状。PyTorch 中常用的调整形状方法有 `reshape()` 和 `view()`。

- `reshape()`：按照指定形状重新组织张量。只要调整前后的元素总数一致，就可以完成形状转换；如果原张量在内存中不连续，`reshape()` 会在需要时自动处理。
- `view()`：也可以按照指定形状重新组织张量，但它要求张量在内存中是连续的。如果张量经过 `transpose()`、`permute()` 等操作后变得不连续，直接使用 `view()` 可能会报错。

注意：无论使用 `reshape()` 还是 `view()`，调整前后的元素总数必须保持一致。例如，形状为 `(2, 3)` 的张量一共有 6 个元素，因此可以调整为 `(3, 2)`、`(6,)` 或 `(1, 6)`，但不能调整为 `(4, 2)`。

In [23]:
# reshape()：调整张量形状
tensor4 = torch.arange(1, 13)

print("原始张量:")
print(tensor4)
print("原始形状:", tensor4.shape)

print("\n使用 reshape(3, 4) 后:")
print(tensor4.reshape(3, 4))
print("调整后的形状:", tensor4.reshape(3, 4).shape)

print("\n使用 reshape(2, 2, 3) 后:")
print(tensor4.reshape(2, 2, 3))
print("调整后的形状:", tensor4.reshape(2, 2, 3).shape)

原始张量:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
原始形状: torch.Size([12])

使用 reshape(3, 4) 后:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
调整后的形状: torch.Size([3, 4])

使用 reshape(2, 2, 3) 后:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
调整后的形状: torch.Size([2, 2, 3])


In [24]:
# reshape() 中可以使用 -1 自动推断某一个维度的大小
tensor5 = torch.arange(1, 25)

print("原始形状:", tensor5.shape)
print("reshape(2, 3, -1) 后的形状:", tensor5.reshape(2, 3, -1).shape)
print(tensor5.reshape(2, 3, -1))

原始形状: torch.Size([24])
reshape(2, 3, -1) 后的形状: torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [25]:
# view()：调整连续张量的形状
tensor6 = torch.arange(1, 13).reshape(3, 4)

print("原始张量:")
print(tensor6)
print("原始形状:", tensor6.shape)

print("\n使用 view(2, 6) 后:")
print(tensor6.view(2, 6))
print("调整后的形状:", tensor6.view(2, 6).shape)

原始张量:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
原始形状: torch.Size([3, 4])

使用 view(2, 6) 后:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
调整后的形状: torch.Size([2, 6])


In [27]:
# view() 要求张量在内存中连续
tensor7 = torch.arange(1, 13).reshape(3, 4)
tensor7_t = tensor7.T

'''
张量转置以后会变得不连续的原因：
转置只是改变了我们“查看张量”的方式，
比如把行和列交换了，
但底层内存中的数据顺序并没有马上重新排列。

所以转置后的张量虽然在逻辑上变了形状，
但物理存储顺序还是原来的顺序。

因此，转置后看起来相邻的元素，
在真实内存中可能并不是挨着存放的，
所以张量通常会变得不连续。
'''

print("转置后的张量是否连续:", tensor7_t.is_contiguous())

# 转置后的张量通常不是连续的，直接 view() 可能会报错
# 可以先使用 contiguous() 得到连续张量，再使用 view()
print("\n先 contiguous()，再 view(2, 6):")
print(tensor7_t.contiguous().view(2, 6))

# reshape() 会在需要时自动处理非连续张量，因此使用起来更灵活
print("\n直接使用 reshape(2, 6):")
print(tensor7_t.reshape(2, 6))

转置后的张量是否连续: False

先 contiguous()，再 view(2, 6):
tensor([[ 1,  5,  9,  2,  6, 10],
        [ 3,  7, 11,  4,  8, 12]])

直接使用 reshape(2, 6):
tensor([[ 1,  5,  9,  2,  6, 10],
        [ 3,  7, 11,  4,  8, 12]])


### 增加或删除维度

有时候张量的数据本身不需要改变，只是需要增加或删除某个维度。比如模型通常要求输入带有 batch 维度，即使只有一条数据，也要把形状从 `(3,)` 调整为 `(1, 3)`。

- `unsqueeze(dim)`：在指定位置增加一个大小为 1 的维度。
- `squeeze(dim)`：删除指定位置上大小为 1 的维度。
- `squeeze()`：如果不指定维度，会删除所有大小为 1 的维度。

注意：`squeeze()` 只能删除大小为 1 的维度，大小不是 1 的维度不会被删除。

In [28]:
# unsqueeze()：增加一个维度
# 这里先创建一个一维张量，可以理解成一条样本，有 3 个特征
x = torch.tensor([10, 20, 30])

print("原始张量:")
print(x)
print("原始形状:", x.shape)

# 在第 0 维增加一个维度，相当于增加 batch 维度
# 形状从 (3,) 变成 (1, 3)
x_batch = x.unsqueeze(0)
print("\n在第 0 维增加维度后:")
print(x_batch)
print("新的形状:", x_batch.shape)

# 在第 1 维增加一个维度，相当于把一行数据变成一列数据
# 形状从 (3,) 变成 (3, 1)
x_col = x.unsqueeze(1)
print("\n在第 1 维增加维度后:")
print(x_col)
print("新的形状:", x_col.shape)

原始张量:
tensor([10, 20, 30])
原始形状: torch.Size([3])

在第 0 维增加维度后:
tensor([[10, 20, 30]])
新的形状: torch.Size([1, 3])

在第 1 维增加维度后:
tensor([[10],
        [20],
        [30]])
新的形状: torch.Size([3, 1])


In [29]:
# squeeze()：删除大小为 1 的维度
# 这个张量的形状是 (1, 3)，第 0 维的大小是 1
y = torch.tensor([[10, 20, 30]])

print("原始张量:")
print(y)
print("原始形状:", y.shape)

# 删除第 0 维，因为第 0 维的大小是 1
# 形状从 (1, 3) 变成 (3,)
y_squeeze = y.squeeze(0)
print("\n删除第 0 维后:")
print(y_squeeze)
print("新的形状:", y_squeeze.shape)

原始张量:
tensor([[10, 20, 30]])
原始形状: torch.Size([1, 3])

删除第 0 维后:
tensor([10, 20, 30])
新的形状: torch.Size([3])


In [30]:
# squeeze() 不指定维度时，会删除所有大小为 1 的维度
z = torch.zeros(1, 2, 1, 3)

print("原始形状:", z.shape)

# 删除所有大小为 1 的维度
# 形状从 (1, 2, 1, 3) 变成 (2, 3)
z_squeeze_all = z.squeeze()
print("squeeze() 后的形状:", z_squeeze_all.shape)

# 只删除第 2 维，因为第 2 维的大小是 1
# 形状从 (1, 2, 1, 3) 变成 (1, 2, 3)
z_squeeze_dim2 = z.squeeze(2)
print("squeeze(2) 后的形状:", z_squeeze_dim2.shape)

# 第 1 维的大小是 2，不是 1，所以 squeeze(1) 不会改变形状
z_squeeze_dim1 = z.squeeze(1)
print("squeeze(1) 后的形状:", z_squeeze_dim1.shape)

原始形状: torch.Size([1, 2, 1, 3])
squeeze() 后的形状: torch.Size([2, 3])
squeeze(2) 后的形状: torch.Size([1, 2, 3])
squeeze(1) 后的形状: torch.Size([1, 2, 1, 3])


### 张量的拼接操作

当我们有多个张量时，经常需要把它们合并到一起。PyTorch 中常用的拼接方法有 `torch.cat()` 和 `torch.stack()`。

- `torch.cat()`：按照已有维度拼接张量。除了拼接的那个维度，其他维度的大小必须相同。
- `torch.stack()`：按照一个新的维度堆叠张量。参与堆叠的所有张量形状必须完全一致。

简单理解：`cat()` 是把张量接在已有方向上，维度数量不变；`stack()` 是先增加一个新维度，再把张量放到这个新维度上。

In [31]:
# torch.cat()：沿着第 0 维拼接，可以理解成“按行往下接”
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

print("a 的形状:", a.shape)
print("b 的形状:", b.shape)

# dim=0 表示沿着第 0 维拼接
# (2, 3) + (2, 3) -> (4, 3)
cat_dim0 = torch.cat([a, b], dim=0)

print("\n沿第 0 维拼接后:")
print(cat_dim0)
print("拼接后的形状:", cat_dim0.shape)

a 的形状: torch.Size([2, 3])
b 的形状: torch.Size([2, 3])

沿第 0 维拼接后:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
拼接后的形状: torch.Size([4, 3])


In [32]:
# torch.cat()：沿着第 1 维拼接，可以理解成“按列往右接”
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

# dim=1 表示沿着第 1 维拼接
# (2, 3) + (2, 3) -> (2, 6)
cat_dim1 = torch.cat([a, b], dim=1)

print("沿第 1 维拼接后:")
print(cat_dim1)
print("拼接后的形状:", cat_dim1.shape)

沿第 1 维拼接后:
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])
拼接后的形状: torch.Size([2, 6])


In [33]:
# torch.stack()：在新维度上堆叠
# stack() 不会接到原来的维度上，而是会增加一个新维度
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("x 的形状:", x.shape)
print("y 的形状:", y.shape)

# dim=0：在最前面新增一个维度
# (3,) 和 (3,) 堆叠后变成 (2, 3)
stack_dim0 = torch.stack([x, y], dim=0)
print("\nstack dim=0 后:")
print(stack_dim0)
print("形状:", stack_dim0.shape)

# dim=1：在第 1 维新增一个维度
# (3,) 和 (3,) 堆叠后变成 (3, 2)
stack_dim1 = torch.stack([x, y], dim=1)
print("\nstack dim=1 后:")
print(stack_dim1)
print("形状:", stack_dim1.shape)

x 的形状: torch.Size([3])
y 的形状: torch.Size([3])

stack dim=0 后:
tensor([[1, 2, 3],
        [4, 5, 6]])
形状: torch.Size([2, 3])

stack dim=1 后:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
形状: torch.Size([3, 2])


In [34]:
# cat() 和 stack() 的形状对比
m = torch.tensor([[1, 2],
                  [3, 4]])

n = torch.tensor([[5, 6],
                  [7, 8]])

print("m 的形状:", m.shape)
print("n 的形状:", n.shape)

# cat 沿已有维度拼接，维度数量还是 2 个
print("\ncat([m, n], dim=0) 的形状:", torch.cat([m, n], dim=0).shape)

# stack 增加一个新维度，维度数量从 2 个变成 3 个
print("stack([m, n], dim=0) 的形状:", torch.stack([m, n], dim=0).shape)

m 的形状: torch.Size([2, 2])
n 的形状: torch.Size([2, 2])

cat([m, n], dim=0) 的形状: torch.Size([4, 2])
stack([m, n], dim=0) 的形状: torch.Size([2, 2, 2])
