# Pytorch的自动微分模块


In [1]:
import torch

In [3]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor(3.0)
print(x)
print(y)

tensor(10.)
tensor(3.)


In [5]:
# 初始化参数
w = torch.rand(1,1,requires_grad=True)
b = torch.rand(1,1,requires_grad=True)

In [6]:
# 前向传播计算输出值Z
z = w * x + b
print(z)

tensor([[9.5769]], grad_fn=<AddBackward0>)


### 叶子节点和根结点
- 在计算图中x，w，b为叶子节点，叶子节点的数据并非由计算生成，因此是整个计算中的基石，叶子节点**不可以**做`in-place`操作
  - 叶子节点在方向传播的时候会记住梯度
- 最终的loss为根结点

In [7]:
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(y.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [8]:
# 设置损失函数
loss = torch.nn.MSELoss()
loss_value = loss(z,y)
print(loss_value)
print(loss_value.is_leaf)

tensor(43.2553, grad_fn=<MseLossBackward0>)
False


/Users/bowen/miniconda3/envs/ailab/lib/python3.10/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [9]:
# 方向传播
loss_value.backward()


In [10]:
# 查看所有的梯度
print(w.grad)
print(b.grad)

tensor([[131.5376]])
tensor([[13.1538]])
